name: Set Executable Permissions

on: [push]

jobs:
  set-permissions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Grant execute permission to postBuild
      run: chmod +x binder/postBuild

    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add binder/postBuild
        git commit -m 'Set executable permissions on postBuild' || echo "No changes to commit"
        git push
