name: Set Executable Permissions

on: [push]

jobs:
  set-permissions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    - name: Pull latest changes
      run: git pull origin main
      # Replace 'main' with your branch name if different

    - name: Grant execute permission to postBuild
      run: chmod +x binder/postBuild

    - name: Commit and push if changes
      run: |
        git add binder/postBuild
        git diff --quiet && git diff --staged --quiet || (git commit -m 'Set executable permissions on postBuild' && git push)
      # This step checks for changes and commits them if there are any, otherwise does nothing
