name: Set Executable Permissions

on: [push]

jobs:
  set-permissions:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Grant execute permission to postBuild
      run: chmod +x binder/postBuild
      shell: bash

    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m 'Set executable permissions on postBuild'
        git push
